config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :microposts
  root "users#index"
  get '/1/edit', to: 'user#edit', as: 'user_edit'
  get '/goodbye', to: 'goodbyes#index', as: 'patient'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/goodbye.rb
class Goodbye < ApplicationRecord
  def bye
    render html: "byeee"
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 14 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  validates :name, length: { maximum: 14 }, presence: true
  validates :email, confirmation: true , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hola,mundo!”"
  end
end

app/controllers/goodbyes_controller.rb
class GoodbyesController < ApplicationController
  before_action :set_goodbye, only: %i[ show edit update destroy ]

  # GET /goodbyes or /goodbyes.json
  def index
    @goodbyes = Goodbye.all
  end

  # GET /goodbyes/1 or /goodbyes/1.json
  def show
  end

  # GET /goodbyes/new
  def new
    @goodbye = Goodbye.new
  end

  # GET /goodbyes/1/edit
  def edit
  end

  # POST /goodbyes or /goodbyes.json
  def create
    @goodbye = Goodbye.new(goodbye_params)

    respond_to do |format|
      if @goodbye.save
        format.html { redirect_to goodbye_url(@goodbye), notice: "Goodbye was successfully created." }
        format.json { render :show, status: :created, location: @goodbye }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goodbye.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goodbyes/1 or /goodbyes/1.json
  def update
    respond_to do |format|
      if @goodbye.update(goodbye_params)
        format.html { redirect_to goodbye_url(@goodbye), notice: "Goodbye was successfully updated." }
        format.json { render :show, status: :ok, location: @goodbye }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goodbye.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goodbyes/1 or /goodbyes/1.json
  def destroy
    @goodbye.destroy

    respond_to do |format|
      format.html { redirect_to goodbyes_url, notice: "Goodbye was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goodbye
      @goodbye = Goodbye.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goodbye_params
      params.fetch(:goodbye, {})
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy ]

  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goodbyes_helper.rb
module GoodbyesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goodbyes/_form.html.erb
<%= form_with(model: goodbye) do |form| %>
  <% if goodbye.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(goodbye.errors.count, "error") %> prohibited this goodbye from being saved:</h2>

      <ul>
        <% goodbye.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/goodbyes/_goodbye.html.erb
<div id="<%= dom_id goodbye %>">
</div>

app/views/goodbyes/edit.html.erb
<h1>Editing goodbye</h1>

<%= render "form", goodbye: @goodbye %>

<br>

<div>
  <%= link_to "Show this goodbye", @goodbye %> |
  <%= link_to "Back to goodbyes", goodbyes_path %>
</div>

app/views/goodbyes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Goodbyes</h1>

<div id="goodbyes">
  <% @goodbyes.each do |goodbye| %>
    <%= render goodbye %>
    <p>
      <%= link_to "Show this goodbye", goodbye %>
    </p>
  <% end %>
</div>

app/views/goodbyes/new.html.erb
<h1>New goodbye</h1>

<%= render "form", goodbye: @goodbye %>

<br>

<div>
  <%= link_to "Back to goodbyes", goodbyes_path %>
</div>

app/views/goodbyes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @goodbye %>

<div>
  <%= link_to "Edit this goodbye", edit_goodbye_path(@goodbye) %> |
  <%= link_to "Back to goodbyes", goodbyes_path %>

  <%= button_to "Destroy this goodbye", @goodbye, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div id="<%= dom_id micropost %>">
  <p>
    <strong>Content:</strong>
    <%= micropost.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= micropost.user_id %>
  </p>

</div>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Show this micropost", @micropost %> |
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Microposts</h1>

<div id="microposts">
  <% @microposts.each do |micropost| %>
    <%= render micropost %>
    <p>
      <%= link_to "Show this micropost", micropost %>
    </p>
  <% end %>
</div>

<%= link_to "New micropost", new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @micropost %>

<div>
  <%= link_to "Edit this micropost", edit_micropost_path(@micropost) %> |
  <%= link_to "Back to microposts", microposts_path %>

  <%= button_to "Destroy this micropost", @micropost, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: deepskyblue"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>